# Generated by Django 5.2.5 on 2026-02-16 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(db_index=True, max_length=32, unique=True)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('business', models.CharField(blank=True, default='', max_length=120)),
                ('canal_contacto', models.CharField(blank=True, default='', max_length=120)),
                ('pauta', models.CharField(blank=True, default='', max_length=500)),
                ('estado', models.CharField(blank=True, default='', max_length=120)),
                ('responsable', models.CharField(blank=True, default='', max_length=200)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('comentarios', models.TextField(blank=True, default='', max_length=2000)),
                ('cita_efectiva', models.BooleanField(default=False)),
                ('cita_virtual', models.BooleanField(default=False)),
                ('solicitud_credito', models.BooleanField(default=False)),
                ('facturado', models.BooleanField(default=False)),
                ('resultado_solicitud', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_venta', models.CharField(blank=True, default='', max_length=120)),
                ('primer_contacto_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_contacto_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes_digitales',
                'managed': True,
                'indexes': [models.Index(fields=['telefono'], name='clientes_di_telefon_67cc10_idx'), models.Index(fields=['agencia', 'estado'], name='clientes_di_agencia_d8225e_idx'), models.Index(fields=['estado'], name='clientes_di_estado_c1d902_idx')],
                'constraints': [models.UniqueConstraint(fields=('telefono',), name='uniq_clientes_digitales_telefono')],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=32)),
                ('direction', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('body', models.TextField(blank=True, default='')),
                ('wa_message_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, default='sent', max_length=30)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='Digitales.clientesdigitales')),
            ],
            options={
                'db_table': 'digitales_mensajes',
                'ordering': ['created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['telefono', 'created_at'], name='digitales_m_telefon_47902e_idx'), models.Index(fields=['wa_message_id'], name='digitales_m_wa_mess_562f6b_idx')],
            },
        ),
    ]
