# Generated by Django 5.2.5 on 2026-02-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientesdigitales',
            name='uniq_clientes_digitales_telefono',
        ),
        migrations.RemoveIndex(
            model_name='clientesdigitales',
            name='clientes_di_telefon_67cc10_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientesdigitales',
            name='clientes_di_agencia_d8225e_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientesdigitales',
            name='clientes_di_estado_c1d902_idx',
        ),
        migrations.AddField(
            model_name='clientesdigitales',
            name='asesor_digital',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientesdigitales',
            name='asesor_ventas',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
