# Generated by Django 5.2.5 on 2026-02-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0002_remove_clientesdigitales_uniq_clientes_digitales_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaMeta',
            fields=[
                ('id_campana', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_concesionaria', models.IntegerField()),
                ('sucursal', models.CharField(max_length=100)),
                ('nombre_campana', models.CharField(max_length=500)),
                ('inicio_campana', models.DateField(blank=True, null=True)),
                ('fin_campana', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campanas_meta',
                'managed': False,
            },
        ),
    ]
