# Generated by Django 5.2.5 on 2026-03-02 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0003_campanameta'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='citas.clientecomercial'),
        ),
        migrations.CreateModel(
            name='ExpedienteDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('business', models.CharField(blank=True, default='', max_length=120)),
                ('canal_contacto', models.CharField(blank=True, default='', max_length=120)),
                ('pauta', models.CharField(blank=True, default='', max_length=500)),
                ('estado', models.CharField(blank=True, default='', max_length=120)),
                ('asesor_digital', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_ventas', models.CharField(blank=True, default='', max_length=200)),
                ('responsable', models.CharField(blank=True, default='', max_length=200)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('comentarios', models.TextField(blank=True, default='', max_length=2000)),
                ('cita_efectiva', models.BooleanField(default=False)),
                ('cita_virtual', models.BooleanField(default=False)),
                ('solicitud_credito', models.BooleanField(default=False)),
                ('facturado', models.BooleanField(default=False)),
                ('resultado_solicitud', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_venta', models.CharField(blank=True, default='', max_length=120)),
                ('primer_contacto_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_contacto_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='expediente_digital', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'expediente_digital',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='ClientesDigitales',
        ),
    ]
