# Generated by Django 5.2.5 on 2026-03-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0004_alter_mensajewhatsapp_cliente_expedientedigital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedigital',
            name='cita_efectiva',
        ),
        migrations.RemoveField(
            model_name='expedientedigital',
            name='cita_virtual',
        ),
        migrations.RemoveField(
            model_name='expedientedigital',
            name='facturado',
        ),
        migrations.RemoveField(
            model_name='expedientedigital',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='expedientedigital',
            name='resultado_solicitud',
        ),
        migrations.RemoveField(
            model_name='expedientedigital',
            name='solicitud_credito',
        ),
        migrations.RemoveField(
            model_name='expedientedigital',
            name='tipo_venta',
        ),
        migrations.AlterModelTable(
            name='campanameta',
            table='dbo.campanas_meta',
        ),
    ]
