# Generated by Django 5.2.5 on 2026-03-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0005_remove_expedientedigital_cita_efectiva_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campanameta',
            table='campanas_meta',
        ),
    ]
