# Generated by Django 5.2.5 on 2026-03-04 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0006_alter_campanameta_table'),
        ('citas', '0003_rename_folio_venta_pruebamanejo_folio_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ultima_cita',
            field=models.ForeignKey(blank=True, db_column='id_ultima_cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='citas.cita'),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ultima_cita_agendada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
