# Generated by Django 5.2.5 on 2026-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0007_expedientedigital_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='resumen',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='resumen_actualizado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='resumen_fuente',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
