# Generated by Django 5.2.5 on 2026-03-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0008_expedientedigital_resumen_and_more'),
        ('citas', '0004_entregas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(db_index=True, max_length=15)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'digitales_lecturas_whatsapp',
                'managed': True,
            },
        ),
        migrations.RemoveIndex(
            model_name='mensajewhatsapp',
            name='digitales_m_telefon_47902e_idx',
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='numero_asesor',
            field=models.CharField(default='522712638803', max_length=15),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['telefono', 'numero_asesor', 'created_at'], name='digitales_m_telefon_e7ff18_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['numero_asesor', 'created_at'], name='digitales_m_numero__dd78b1_idx'),
        ),
        migrations.AddField(
            model_name='lecturawhatsapp',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_whatsapp', to='Digitales.expedientedigital'),
        ),
        migrations.AddIndex(
            model_name='lecturawhatsapp',
            index=models.Index(fields=['expediente', 'numero_asesor'], name='digitales_l_expedie_2309f7_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturawhatsapp',
            index=models.Index(fields=['numero_asesor', 'last_read_at'], name='digitales_l_numero__641f08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturawhatsapp',
            unique_together={('expediente', 'numero_asesor')},
        ),
    ]
