# Generated by Django 5.2.5 on 2026-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0009_lecturawhatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajewhatsapp',
            name='numero_asesor',
            field=models.CharField(max_length=15),
        ),
    ]
