# Generated by Django 6.0.4 on 2026-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0010_alter_mensajewhatsapp_numero_asesor'),
        ('citas', '0005_entregas_color_entregas_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoFuenteMeta',
            fields=[
                ('id_fuente', models.CharField(db_column='id_fuente', max_length=120, primary_key=True, serialize=False)),
                ('tipo_fuente', models.CharField(max_length=30)),
                ('id_campana', models.BigIntegerField(blank=True, null=True)),
                ('nombre_campana', models.CharField(blank=True, default='', max_length=500)),
                ('id_anuncio', models.BigIntegerField(blank=True, null=True)),
                ('nombre_anuncio', models.CharField(blank=True, default='', max_length=500)),
                ('id_conjunto', models.BigIntegerField(blank=True, null=True)),
                ('nombre_conjunto', models.CharField(blank=True, default='', max_length=500)),
                ('sucursal', models.CharField(blank=True, default='', max_length=100)),
                ('respuesta_meta', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapeo_fuentes_meta',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mensajewhatsapp',
            options={'managed': True, 'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='mensajewhatsapp',
            name='digitales_m_telefon_e7ff18_idx',
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['telefono', 'numero_asesor', 'created_at', 'id'], name='dig_msg_tel_line_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['telefono', 'numero_asesor', '-created_at', '-id'], name='dig_msg_tel_line_desc_idx'),
        ),
    ]
