# Generated by Django 6.0.4 on 2026-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0011_mapeofuentemeta_alter_mensajewhatsapp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientedigital',
            name='pauta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
