# Generated by Django 6.0.4 on 2026-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0012_alter_expedientedigital_pauta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPreciosSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precios_actuales', models.JSONField(default=dict)),
                ('precios_propuestos', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente revisión'), ('aplicado', 'Aplicado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('scraping_exitoso', models.BooleanField(default=False)),
                ('error_scraping', models.TextField(blank=True, default='')),
                ('modelos_fallidos', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('aplicado_por', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'db_table': 'catalogo_precios_snapshot',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
    ]
