# Generated by Django 6.0.4 on 2026-06-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0013_catalogopreciossnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Volkswagen', max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('ano', models.PositiveSmallIntegerField()),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('precio_lista', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_contado', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_financiado', models.PositiveIntegerField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, default='')),
                ('ficha_tecnica', models.JSONField(blank=True, default=dict)),
                ('url_ficha_tecnica', models.CharField(blank=True, default='', max_length=800)),
                ('imagenes', models.JSONField(blank=True, default=list)),
                ('ultima_actualizacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalogo_vehiculos',
                'ordering': ['marca', 'modelo', 'ano', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionIAWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(max_length=15, unique=True)),
                ('activo', models.BooleanField(default=False)),
                ('horarios', models.JSONField(blank=True, default=dict)),
                ('identidad', models.TextField(blank=True, default='')),
                ('precios', models.TextField(blank=True, default='')),
                ('perfilamiento', models.TextField(blank=True, default='')),
                ('limites', models.TextField(blank=True, default='')),
                ('personalidad', models.TextField(blank=True, default='')),
                ('condiciones_fijas', models.TextField(blank=True, default='')),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'db_table': 'configuracion_ia_whatsapp',
                'ordering': ['numero_asesor'],
            },
        ),
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(db_index=True, max_length=15)),
                ('ia_activa', models.BooleanField(default=True)),
                ('ia_pausada', models.BooleanField(default=False)),
                ('motivo_pausa', models.CharField(blank=True, default='', max_length=120)),
                ('estado_conversacion', models.CharField(blank=True, default='sin_iniciar', max_length=50)),
                ('pregunta_pendiente', models.CharField(blank=True, default='', max_length=80)),
                ('pregunta_pendiente_intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultima_intencion', models.CharField(blank=True, default='', max_length=80)),
                ('ultimo_modelo_mencionado', models.CharField(blank=True, default='', max_length=120)),
                ('resumen_conversacion', models.TextField(blank=True, default='')),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'conversacion_ia',
            },
        ),
        migrations.CreateModel(
            name='InteresVehiculoProspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('origen', models.CharField(blank=True, default='ia', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'intereses_vehiculos_prospectos',
            },
        ),
        migrations.DeleteModel(
            name='CatalogoPreciosSnapshot',
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='buro_estado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='cotizacion_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='cotizacion_solicitada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='enganche_monto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='forma_pago',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ia_pausada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ia_pausada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ia_pausada_motivo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='motivo_requiere_asesor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='plazo_compra',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='presupuesto_mensual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='requiere_asesor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='tipo_cliente',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='uso_vehiculo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='catalogovehiculos',
            index=models.Index(fields=['marca', 'modelo', 'ano'], name='catalogo_ve_marca_e40f50_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogovehiculos',
            index=models.Index(fields=['activo'], name='catalogo_ve_activo_372d30_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogovehiculos',
            index=models.Index(fields=['modelo'], name='catalogo_ve_modelo_6ad1e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogovehiculos',
            constraint=models.UniqueConstraint(fields=('marca', 'modelo', 'ano', 'version'), name='uniq_catalogo_vehiculos_modelo_version'),
        ),
        migrations.AddField(
            model_name='conversacionia',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia', to='Digitales.expedientedigital'),
        ),
        migrations.AddField(
            model_name='interesvehiculoprospecto',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intereses_vehiculos', to='Digitales.expedientedigital'),
        ),
        migrations.AddIndex(
            model_name='conversacionia',
            index=models.Index(fields=['numero_asesor', 'ia_activa', 'ia_pausada'], name='conversacio_numero__3a09ff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionia',
            index=models.Index(fields=['estado_conversacion'], name='conversacio_estado__03b8c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversacionia',
            unique_together={('expediente', 'numero_asesor')},
        ),
        migrations.AddIndex(
            model_name='interesvehiculoprospecto',
            index=models.Index(fields=['expediente', 'activo'], name='intereses_v_expedie_2c2fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='interesvehiculoprospecto',
            index=models.Index(fields=['modelo'], name='intereses_v_modelo_e799e7_idx'),
        ),
    ]
