# Generated by Django 6.0.4 on 2026-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0014_catalogovehiculos_configuracioniawhatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='comprobacion_ingresos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
