# Generated by Django 6.0.4 on 2026-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0015_expedientedigital_comprobacion_ingresos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedigital',
            name='primer_contacto_at',
        ),
        migrations.RemoveField(
            model_name='expedientedigital',
            name='ultimo_contacto_at',
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='primer_contacto_asesor',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='primer_mensaje_cliente',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='ultimo_contacto_asesor',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
