# Generated by Django 6.0.4 on 2026-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0016_remove_expedientedigital_primer_contacto_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioniawhatsapp',
            name='promociones_eventos',
            field=models.TextField(blank=True, default=''),
        ),
    ]
