# Generated by Django 6.0.4 on 2026-06-23 17:36

import Digitales.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0017_configuracioniawhatsapp_promociones_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='folio_solicitud_credito',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='id_cotizacion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='solicitud_credito_estado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='vin_estatus_entrega',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='vin_facturado',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='EvidenciaProspectoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to=Digitales.models.evidencia_prospecto_upload_path)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('subido_por', models.CharField(blank=True, default='', max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='Digitales.expedientedigital')),
            ],
            options={
                'db_table': 'expediente_digital_evidencias',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['expediente', '-creado'], name='expediente__expedie_288e84_idx')],
            },
        ),
    ]
