# Generated by Django 6.0.4 on 2026-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0018_expedientedigital_folio_solicitud_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogovehiculos',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
