# Generated by Django 6.0.4 on 2026-07-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0019_catalogovehiculos_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='whatsapp_bloqueado_respuesta_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
