# Generated by Django 6.0.4 on 2026-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0020_expedientedigital_whatsapp_bloqueado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='motivo_descalificacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
