# Generated by Django 6.0.4 on 2026-07-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0022_expedientedigital_anio_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogovehiculos',
            name='ficha_tecnica_thumbnail',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
