# Generated by Django 6.0.4 on 2026-07-29 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0023_catalogovehiculos_ficha_tecnica_thumbnail'),
        ('citas', '0009_entregas_kilometraje'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAsesorDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_asesor', models.CharField(blank=True, db_index=True, default='', max_length=15)),
                ('asesor_digital', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('usuario_crm', models.CharField(blank=True, default='', max_length=120)),
                ('tipo', models.CharField(blank=True, db_index=True, default='otro', max_length=80)),
                ('accion', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, default='', max_length=1000)),
                ('plantilla_nombre', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('resultado', models.CharField(blank=True, db_index=True, default='pendiente', max_length=80)),
                ('estado_entrega', models.CharField(blank=True, default='', max_length=50)),
                ('respuesta_texto', models.TextField(blank=True, default='', max_length=1000)),
                ('respondido_at', models.DateTimeField(blank=True, null=True)),
                ('tiempo_respuesta_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_digital', to='citas.clientecomercial')),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_asesor', to='Digitales.expedientedigital')),
                ('mensaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_asesor', to='Digitales.mensajewhatsapp')),
                ('respuesta_mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Digitales.mensajewhatsapp')),
            ],
            options={
                'db_table': 'digitales_bitacora_asesor',
                'ordering': ['-creado', '-id'],
                'indexes': [models.Index(fields=['numero_asesor', '-creado'], name='digitales_b_numero__4af3db_idx'), models.Index(fields=['expediente', 'numero_asesor', '-creado'], name='digitales_b_expedie_0b4721_idx'), models.Index(fields=['tipo', 'resultado', '-creado'], name='digitales_b_tipo_7aa2ec_idx'), models.Index(fields=['plantilla_nombre', '-creado'], name='digitales_b_plantil_57fd25_idx')],
            },
        ),
    ]
