# Generated by Django 6.0.4 on 2026-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0024_bitacoraasesordigital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRepartoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(db_index=True, max_length=15, unique=True)),
                ('siguiente_indice', models.PositiveIntegerField(default=0)),
                ('ultimo_usuario', models.CharField(blank=True, default='', max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'digitales_control_reparto_whatsapp',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='asignado_automaticamente_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='usuario_crm_asignado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
