# Generated by Django 6.0.4 on 2026-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0025_controlrepartowhatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientedigital',
            name='facturado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='expedientedigital',
            name='facturado_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
