# Generated by Django 6.0.4 on 2026-08-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0026_expedientedigital_facturado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientedigital',
            name='facturado',
        ),
    ]
