# Generated by Django 5.2.5 on 2026-08-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0016_alter_usuario_telefono'),
        ('Digitales', '0027_remove_expedientedigital_facturado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRapidaAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_rapidas', to='CrmConformidad.usuario')),
            ],
            options={
                'db_table': 'respuestas_rapidas_asesor',
                'ordering': ['-creado', '-id'],
                'indexes': [models.Index(fields=['usuario', '-creado'], name='respuestas__usuario_c2e74c_idx')],
            },
        ),
    ]
