# Generated by Django 5.2.5 on 2026-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0028_respuestarapidaasesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('telefono', models.CharField(blank=True, db_index=True, default='', max_length=25)),
                ('tipo_asesor', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('area', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('agencia', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'digitales_catalogo_asesor',
                'ordering': ['nombre', 'agencia'],
            },
        ),
    ]
