# Generated by Django 5.2.5 on 2026-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0028_respuestarapidaasesor'),
        ('citas', '0013_add_prueba_manejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='from_ia',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='expedientedigital',
            index=models.Index(fields=['estado'], name='dig_exp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajewhatsapp',
            index=models.Index(fields=['telefono', 'numero_asesor', 'direction', 'from_ia'], name='dig_msg_contact_check_idx'),
        ),
    ]
