# Generated by Django 6.0.4 on 2026-09-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0029_asesor'),
        ('Digitales', '0029_mensajewhatsapp_from_ia_and_more'),
    ]

    operations = [
    ]
