# Generated by Django 5.2.5 on 2026-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0030_merge_20260901_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('tipo_personal', models.CharField(blank=True, db_index=True, default='Tecnico', max_length=80)),
                ('agencia', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'digitales_catalogo_tecnico',
                'ordering': ['nombre', 'agencia'],
            },
        ),
    ]
