# Generated by Django 6.0.4 on 2026-10-02 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digitales', '0032_cargar_personal_tuxtepec'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoWhatsAppLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(db_index=True, max_length=15)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('bloqueado_por', models.CharField(blank=True, default='', max_length=120)),
                ('respuesta_meta', models.JSONField(blank=True, default=dict)),
                ('bloqueado_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_whatsapp', to='Digitales.expedientedigital')),
            ],
            options={
                'db_table': 'digitales_bloqueo_whatsapp_linea',
                'indexes': [models.Index(fields=['numero_asesor', 'expediente'], name='dig_bloqueo_linea_idx')],
                'constraints': [models.UniqueConstraint(fields=('expediente', 'numero_asesor'), name='uniq_bloqueo_whatsapp_linea')],
            },
        ),
    ]
