# Generated by Django 6.0.4 on 2026-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VWVN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, db_column='Serie', max_length=255, null=True)),
                ('nr_nota', models.IntegerField(blank=True, db_column='NrNota', null=True)),
                ('tp_producto', models.CharField(blank=True, db_column='TpProduto', max_length=255, null=True)),
                ('producto_servicio', models.CharField(blank=True, db_column='ProdOuServ', max_length=255, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='PrcUnitario', decimal_places=3, max_digits=18, null=True)),
                ('valor_bruto_item', models.DecimalField(blank=True, db_column='VrBrutoItem', decimal_places=3, max_digits=18, null=True)),
                ('influye_estadistica', models.CharField(blank=True, db_column='InfluiEstat', max_length=255, null=True)),
                ('valor_descuento_item', models.DecimalField(blank=True, db_column='VrDescItem', decimal_places=3, max_digits=18, null=True)),
                ('codigo_condicion_pago', models.CharField(blank=True, db_column='CodCondPgto', max_length=255, null=True)),
                ('valor_factura', models.DecimalField(blank=True, db_column='ValorFactura', decimal_places=3, max_digits=18, null=True)),
                ('valor_factura_sin_iva', models.DecimalField(blank=True, db_column='ValorFacturaSnIva', decimal_places=3, max_digits=18, null=True)),
                ('valor_compra', models.DecimalField(blank=True, db_column='ValorCompra', decimal_places=3, max_digits=18, null=True)),
                ('isan', models.DecimalField(blank=True, db_column='ISAN', decimal_places=3, max_digits=18, null=True)),
                ('iva', models.DecimalField(blank=True, db_column='IVA', decimal_places=3, max_digits=18, null=True)),
                ('codigo_entidad', models.IntegerField(blank=True, db_column='CodEntidade', null=True)),
                ('fecha_emision', models.DateField(blank=True, db_column='DtEmissao', null=True)),
                ('situacion', models.CharField(blank=True, db_column='Situacao', max_length=255, null=True)),
                ('tipo_nf', models.CharField(blank=True, db_column='TpNF', max_length=255, null=True)),
                ('nr_mov', models.IntegerField(blank=True, db_column='NrMov', null=True)),
                ('fecha_ultima_venta', models.DateField(blank=True, db_column='DrUltVenda', null=True)),
                ('razon_social', models.CharField(blank=True, db_column='RazaoSocial', max_length=255, null=True)),
                ('tipo_persona', models.CharField(blank=True, db_column='TpPessoa', max_length=255, null=True)),
                ('valor_total_productos', models.DecimalField(blank=True, db_column='VrTotalProds', decimal_places=3, max_digits=18, null=True)),
                ('codigo_marca', models.CharField(blank=True, db_column='CodMarca', max_length=255, null=True)),
                ('nombre_marca', models.CharField(blank=True, db_column='NmMarca', max_length=255, null=True)),
                ('nombre_familia', models.CharField(blank=True, db_column='NmFamilia', max_length=255, null=True)),
                ('condicion_uso', models.CharField(blank=True, db_column='CondUso', max_length=255, null=True)),
                ('nombre_condicion_pago', models.CharField(blank=True, db_column='NmCondPgto', max_length=255, null=True)),
                ('asesor', models.CharField(blank=True, db_column='Asesor', max_length=255, null=True)),
                ('agencia', models.CharField(blank=True, db_column='AGENCIA', max_length=255, null=True)),
            ],
            options={
                'db_table': 'VW_VN',
                'managed': False,
            },
        ),
    ]
