# Generated by Django 5.2.5 on 2026-04-07 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSafety',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.localdate)),
                ('reportante', models.CharField(max_length=200)),
                ('agencia', models.CharField(max_length=200)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('orden_servicio', models.CharField(max_length=100)),
                ('tecnico_reparo', models.CharField(max_length=200)),
                ('valido_control_calidad', models.CharField(max_length=200)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('comentarios_finales', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'safety_reportes',
                'ordering': ['-creado', '-id_reporte'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoReporteSafety',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('punto_checklist_id', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_adjunto', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('archivo', 'Archivo')], default='archivo', max_length=20)),
                ('archivo', models.FileField(upload_to='safety/reportes/%Y/%m/%d/')),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=200)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='Safety.reportesafety')),
            ],
            options={
                'db_table': 'safety_reportes_adjuntos',
                'ordering': ['id_adjunto'],
                'managed': True,
            },
        ),
    ]
