# Generated by Django 5.2.5 on 2026-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntoreportesafety',
            name='punto_checklist_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='adjuntoreportesafety',
            index=models.Index(fields=['reporte', 'punto_checklist_id'], name='safety_rep_punto_idx'),
        ),
        migrations.AddIndex(
            model_name='adjuntoreportesafety',
            index=models.Index(fields=['reporte', 'tipo_adjunto'], name='safety_rep_tipo_idx'),
        ),
    ]
