# Generated by Django 5.2.5 on 2026-09-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrmConformidad', '0016_alter_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asesor', models.CharField(db_index=True, max_length=20)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('wa_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('expediente_id', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_whatsapp', to='CrmConformidad.usuario')),
            ],
            options={
                'db_table': 'notificaciones_whatsapp_notificacion',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['usuario', 'leida', 'creado'], name='notificacio_usuario_b60316_idx')],
            },
        ),
    ]
