# Generated by Django 6.0.4 on 2026-08-26 16:11

import django.core.validators
import django.db.models.deletion
import documentacion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(default=documentacion.models.generar_folio, editable=False, max_length=30, unique=True)),
                ('cliente', models.CharField(max_length=250)),
                ('agencia', models.CharField(db_index=True, max_length=150)),
                ('tipo_persona', models.CharField(choices=[('fisica_asalariada', 'Persona Física Asalariada'), ('fisica_profesionista', 'Persona Física Profesionista'), ('moral', 'Persona Moral')], max_length=30)),
                ('financiamiento', models.CharField(choices=[('credit', 'Credit'), ('leasing', 'Leasing')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_documentacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documentacion_expedientes',
                'ordering': ['-creado', '-id_expediente'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('requisito_id', models.CharField(db_index=True, max_length=100)),
                ('requisito_nombre', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to=documentacion.models.ruta_documento, validators=[django.core.validators.FileExtensionValidator(['pdf']), documentacion.models.validar_pdf_real])),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(default='application/pdf', max_length=150)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentacion.expediente')),
            ],
            options={
                'db_table': 'documentacion_expedientes_documentos',
                'ordering': ['id_documento'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['asesor', 'creado'], name='doc_exp_asesor_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['agencia', 'creado'], name='doc_exp_agencia_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoexpediente',
            index=models.Index(fields=['expediente', 'requisito_id'], name='doc_exp_req_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentoexpediente',
            constraint=models.UniqueConstraint(fields=('expediente', 'requisito_id'), name='doc_unico_por_requisito'),
        ),
    ]
