# Generated by Django 6.0.4 on 2026-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expediente',
            name='doc_exp_asesor_idx',
        ),
        migrations.AddField(
            model_name='expediente',
            name='asesor_nombre',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='expediente',
            name='creado_por',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['asesor_nombre', 'creado'], name='doc_exp_asesor_idx'),
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='asesor',
        ),
    ]
