# Generated by Django 6.0.4 on 2026-08-29 09:06

import django.core.validators
import documentacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_remove_expediente_doc_exp_asesor_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='solicitud_pdf',
            field=models.FileField(blank=True, null=True, upload_to=documentacion.models.ruta_solicitud_pdf, validators=[django.core.validators.FileExtensionValidator(['pdf']), documentacion.models.validar_pdf_real]),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitud_pdf_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitud_pdf_campos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitud_pdf_plantilla',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
