# Generated by Django 5.2.5 on 2026-09-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_expediente_solicitud_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentoexpediente',
            name='doc_unico_por_requisito',
        ),
        migrations.AddConstraint(
            model_name='documentoexpediente',
            constraint=models.UniqueConstraint(condition=models.Q(('requisito_id', 'otros'), _negated=True), fields=('expediente', 'requisito_id'), name='doc_unico_por_requisito'),
        ),
    ]
