# Generated by Django 5.2.5 on 2026-03-13 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0003_rename_folio_venta_pruebamanejo_folio_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaluoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('fecha_avaluo', models.DateTimeField(blank=True, null=True)),
                ('asesor_ventas', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('marca_auto', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('anio_modelo', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('serie', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('kilometraje', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('precio_guia', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('costo_reparacion', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('oferta_economica', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('ganador_subasta', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('etapa_proceso', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('comentarios', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='avaluos_usados', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'avaluos',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
    ]
