# Generated by Django 5.2.5 on 2026-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluousado',
            name='tipo_toma',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
