# Generated by Django 6.0.4 on 2026-04-21 09:55

import django.db.models.deletion
import usados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usados', '0002_avaluousado_tipo_toma'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluousado',
            name='color',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='avaluousado',
            name='costo_estimado',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='avaluousado',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.CreateModel(
            name='AvaluoUsadoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=usados.models.avaluo_evidencia_upload_to)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('archivo', 'Archivo')], default='archivo', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('avaluo', models.ForeignKey(db_column='id_avaluo', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='usados.avaluousado')),
            ],
            options={
                'db_table': 'avaluos_evidencias',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConceptoAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', max_length=4000)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('avaluo', models.ForeignKey(db_column='id_avaluo', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='usados.avaluousado')),
            ],
            options={
                'db_table': 'conceptos_avaluos',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
