# Generated by Django 5.2.5 on 2026-10-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usados', '0004_avaluousado_tipo_valuacion_vendedor_origen_y_mas'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluousado',
            name='checklist_cpo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
