#ryrback/settings.py
"""
Django settings for ryrback project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2478i0#18$^(_3_2kqzix8a5zeazw%rbxa)b85%sor1b(&jul+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',

    "encuesta-automotriz-ryr-oba.vercel.app",
    "encuesta-automotriz-ryr-cba.vercel.app",
    "encuesta-automotriz-ryr-txp.vercel.app",
    "encuesta-automotriz-ryr-pz.vercel.app",
    "encuesta-automotriz-ryr-txt.vercel.app",

    "encuesta-servicio-ryr-cba.vercel.app",
    "encuesta-servicio-ryr-oba.vercel.app",
    "encuesta-servicio-ryr-txp.vercel.app",
    "encuesta-servicio-ryr-pz.vercel.app",
    "encuesta-servicio-ryr-txt.vercel.app",
    "reporte-control-calidad.vercel.app",
    "grupoautomotrizryr.com",
    "www.grupoautomotrizryr.com",
    "crm.grupoautomotrizryr.com",
    "191.96.31.18",
    "trafico-piso.vercel.app",
    "concertacion-citas.vercel.app",
    "entregas-vw.vercel.app",

    "graficos-entrega-cba.vercel.app",
    "graficos-entrega-oba.vercel.app",
    "graficos-entrega-txp.vercel.app",
    "graficos-entrega-pzr.vercel.app",
    "graficos-entrega-txt.vercel.app",

    "attentive-endearing-bargraph.ngrok-free.dev",
    "hoja-ingresos-cba.vercel.app",
    "hoja-ingresos-oba.vercel.app",
    "visualiza-citas-vw.vercel.app",
]


CSRF_TRUSTED_ORIGINS = [
    "https://encuesta-automotriz-ryr-oba.vercel.app",
    "https://encuesta-automotriz-ryr-cba.vercel.app",
    "https://encuesta-automotriz-ryr-txp.vercel.app",
    "https://encuesta-automotriz-ryr-txt.vercel.app",
    "https://encuesta-automotriz-ryr-pz.vercel.app",

    "https://encuesta-servicio-ryr-cba.vercel.app",
    "https://encuesta-servicio-ryr-oba.vercel.app",
    "https://encuesta-servicio-ryr-txp.vercel.app",
    "https://encuesta-servicio-ryr-pz.vercel.app",
    "https://encuesta-servicio-ryr-txt.vercel.app",
    
    "https://grupoautomotrizryr.com",
    "https://www.grupoautomotrizryr.com",
    "https://c7b2-2806-10a6-24-5453-416b-6048-7bd7-2b81.ngrok-free.app",
    "https://crm.grupoautomotrizryr.com",
    "https://reporte-control-calidad.vercel.app",

    "https://trafico-piso.vercel.app",
    "https://concertacion-citas.vercel.app",
    "https://entregas-vw.vercel.app",

    "https://graficos-entrega-cba.vercel.app",
    "https://graficos-entrega-oba.vercel.app",
    "https://graficos-entrega-txp.vercel.app",
    "https://graficos-entrega-pzr.vercel.app",
    "https://graficos-entrega-txt.vercel.app",
    
    "https://bitacora-mantenimiento-showroom.vercel.app",
    "https://attentive-endearing-bargraph.ngrok-free.dev",
    "https://hoja-ingresos-cba.vercel.app",
    "https://hoja-ingresos-oba.vercel.app",
    "https://visualiza-citas-vw.vercel.app",
]

# Application definition

INSTALLED_APPS = [
    "channels",
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'CrmConformidad',
    "citas.apps.CitasConfig",
    'Digitales',
    "notificaciones",
    "clickup",
    "Financieros",
    "usados",
    "Encuestas",
    "PedidosPiezas",
    "Safety",
    "rrhh",
    'trafico_piso',
    'meta_ads',
    'retencion',
    'jdpower',
    'hojaingresos',
    'inventario',
    'flujo',
    "BitacoraMantenimiento",
    "documentacion",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#REST_FRAMEWORK = {
#    "DEFAULT_AUTHENTICATION_CLASSES": [
#        "CrmConformidad.authentication.SignedUserAuthentication",
#    ],
#    "DEFAULT_PERMISSION_CLASSES": [
#        "rest_framework.permissions.IsAuthenticated",
#    ],
#}

ROOT_URLCONF = 'ryrback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOW_CREDENTIALS = True
WSGI_APPLICATION = "ryrback.wsgi.application"
ASGI_APPLICATION = "ryrback.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6380)],
        }
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:8000",
    "https://grupoautomotrizryr.com",
    "https://www.grupoautomotrizryr.com",
    "https://crm.grupoautomotrizryr.com",
    "https://reporte-control-calidad.vercel.app",
    
    "https://encuesta-automotriz-ryr-oba.vercel.app",
    "https://encuesta-automotriz-ryr-cba.vercel.app",
    "https://encuesta-automotriz-ryr-txp.vercel.app",
    "https://encuesta-automotriz-ryr-txt.vercel.app",
    "https://encuesta-automotriz-ryr-pz.vercel.app",

    "https://encuesta-servicio-ryr-cba.vercel.app",
    "https://encuesta-servicio-ryr-oba.vercel.app",
    "https://encuesta-servicio-ryr-txp.vercel.app",
    "https://encuesta-servicio-ryr-pz.vercel.app",
    "https://encuesta-servicio-ryr-txt.vercel.app",

    "https://trafico-piso.vercel.app",
    "https://concertacion-citas.vercel.app",
    "https://entregas-vw.vercel.app",

    "https://graficos-entrega-cba.vercel.app",
    "https://graficos-entrega-oba.vercel.app",
    "https://graficos-entrega-txp.vercel.app",
    "https://graficos-entrega-pzr.vercel.app",
    "https://graficos-entrega-txt.vercel.app",

    "https://bitacora-mantenimiento-showroom.vercel.app",
    "https://attentive-endearing-bargraph.ngrok-free.dev",
    "https://hoja-ingresos-cba.vercel.app",
    "https://hoja-ingresos-oba.vercel.app",
    "https://visualiza-citas-vw.vercel.app",
]


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "crm_ryr",
        "USER": "israel",
        "PASSWORD": "CRMR&R2026@",
#        "HOST": "127.0.0.1",
        "HOST": "191.96.31.18",
        "PORT": "5432",
    },

    'sqlserver': {
        'ENGINE': 'mssql',
        'NAME': 'TotalDealer_CO',
        'USER': 'Israel',
        'PASSWORD': 'Isr4el@2025',
        'HOST': '187.141.69.254',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            "extra_params": "TrustServerCertificate=yes",
        }
    },
    'sqlserver_inv': {
        'ENGINE': 'mssql',
        'NAME': 'TDSQL_VW',
        'USER': 'Israel',
        'PASSWORD': 'Isr4el@2025',
        'HOST': '187.141.69.254',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            "extra_params": "TrustServerCertificate=yes",
        }
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = "America/Mexico_City"
USE_I18N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@crm.local"
PUBLIC_API_BASE_URL = "https://crm.grupoautomotrizryr.com"
OPENAI_API_KEY = ""
GEMINI_API_KEY = ""
GEMINI_MULTIMODAL_MODEL = "gemini-3.7-flash"
GEMINI_MAX_INLINE_MEDIA_BYTES = 18 * 1024 * 1024
GEMINI_RESULTS_TIMEOUT_MS = 45000

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "CrmConformidad.jwt_authentication.CRMJWTAuthentication",
    ),
}