# Generated by Django 5.2.5 on 2026-06-30 16:14

import BitacoraMantenimiento.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('chasis_vin', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('anio_modelo_color', models.CharField(blank=True, max_length=100)),
                ('responsable', models.CharField(max_length=150)),
                ('fecha_captura', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactivo_id', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('na', 'N/A')], max_length=2, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivos', to='BitacoraMantenimiento.bitacora')),
            ],
            options={
                'ordering': ['reactivo_id'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=BitacoraMantenimiento.models.ruta_evidencia)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='BitacoraMantenimiento.reactivo')),
            ],
        ),
    ]
