# Generated by Django 6.0.4 on 2026-04-27 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacanteReclutamiento',
            fields=[
                ('id_vacante', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(default='Publicada', max_length=50)),
                ('puesto', models.CharField(max_length=150)),
                ('dealer', models.CharField(max_length=150)),
                ('solicitado_por', models.CharField(max_length=150)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vacante de reclutamiento',
                'verbose_name_plural': 'Vacantes de reclutamiento',
                'db_table': 'rrhh_vacantes_reclutamiento',
                'ordering': ['-id_vacante'],
            },
        ),
    ]
