# Generated by Django 6.0.4 on 2026-04-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantereclutamiento',
            name='fuente_reclutamiento',
            field=models.CharField(default='Base de datos', max_length=80),
        ),
        migrations.CreateModel(
            name='CandidatoReclutamiento',
            fields=[
                ('id_candidato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('sexo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=180)),
                ('ubicacion', models.CharField(max_length=180)),
                ('puesto_postulado', models.CharField(max_length=150)),
                ('fuente', models.CharField(max_length=80)),
                ('estatus', models.CharField(default='Nuevo', max_length=50)),
                ('fecha_entrevista_do', models.DateField(blank=True, null=True)),
                ('fecha_entrevista_gerente', models.DateField(blank=True, null=True)),
                ('fecha_respuesta_gerente', models.DateField(blank=True, null=True)),
                ('fecha_alta_khor', models.DateField(blank=True, null=True)),
                ('fecha_realizacion_khor', models.DateField(blank=True, null=True)),
                ('fecha_entrega_resultados_khor', models.DateField(blank=True, null=True)),
                ('tipo_validacion_socioeconomica', models.CharField(default='No aplica', max_length=80)),
                ('fecha_solicitud_estudio_socioeconomico', models.DateField(blank=True, null=True)),
                ('fecha_entrega_reporte_socioeconomico', models.DateField(blank=True, null=True)),
                ('fecha_solicitud_referencias_laborales', models.DateField(blank=True, null=True)),
                ('fecha_entrega_referencias_laborales', models.DateField(blank=True, null=True)),
                ('fecha_solicitud_alta', models.DateField(blank=True, null=True)),
                ('fecha_respuesta_alta', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='rrhh.vacantereclutamiento')),
            ],
            options={
                'verbose_name': 'Candidato de reclutamiento',
                'verbose_name_plural': 'Candidatos de reclutamiento',
                'db_table': 'rrhh_candidatos_reclutamiento',
                'ordering': ['-id_candidato'],
            },
        ),
    ]
