# Generated by Django 6.0.4 on 2026-05-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_vacantereclutamiento_fuente_reclutamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'rrhh_puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPuesto',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('colaborador_nombre', models.CharField(max_length=200)),
                ('periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('concesionario', models.CharField(blank=True, max_length=200, null=True)),
                ('antiguedad', models.CharField(blank=True, max_length=50, null=True)),
                ('evaluador_nombre', models.CharField(max_length=200)),
                ('evaluador_puesto', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo', models.CharField(choices=[('A', 'Análisis de desempeño'), ('D', 'Desarrollo del trabajador'), ('E', 'Evaluación directa')], default='A', max_length=1)),
                ('respuestas', models.JSONField(default=dict)),
                ('calificacion', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='rrhh.puesto')),
            ],
            options={
                'verbose_name': 'Evaluación de puesto',
                'verbose_name_plural': 'Evaluaciones de puestos',
                'db_table': 'rrhh_evaluaciones_puestos',
                'ordering': ['-fecha'],
            },
        ),
    ]
