# Generated by Django 6.0.4 on 2026-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_puesto_evaluacionpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatoreclutamiento',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='reclutamiento/cvs/'),
        ),
    ]
