# Generated by Django 6.0.4 on 2026-07-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_candidatoreclutamiento_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('nss', models.CharField(blank=True, default='', max_length=20)),
                ('curp', models.CharField(blank=True, default='', max_length=18)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rrhh_colaboradores',
                'ordering': ['nombre'],
            },
        ),
    ]
