# Generated by Django 6.0.4 on 2026-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True),
        ),
    ]
