# Generated by Django 6.0.4 on 2026-07-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_colaborador_activo_colaborador_motivo_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAmbienteLaboral',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría (Ambiente laboral)',
                'verbose_name_plural': 'Categorías (Ambiente laboral)',
                'db_table': 'rrhh_al_categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DominioAmbienteLaboral',
            fields=[
                ('id_dominio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='rrhh.categoriaambientelaboral')),
            ],
            options={
                'verbose_name': 'Dominio (Ambiente laboral)',
                'verbose_name_plural': 'Dominios (Ambiente laboral)',
                'db_table': 'rrhh_al_dominios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionAmbienteLaboral',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('dealer', models.CharField(max_length=150)),
                ('anio', models.PositiveIntegerField()),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('plan_accion', models.TextField(blank=True, default='')),
                ('seguimiento', models.TextField(blank=True, default='')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='ambiente_laboral/evidencias/')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='rrhh.dominioambientelaboral')),
            ],
            options={
                'verbose_name': 'Evaluación (Ambiente laboral)',
                'verbose_name_plural': 'Evaluaciones (Ambiente laboral)',
                'db_table': 'rrhh_al_evaluaciones',
                'ordering': ['dominio__categoria__orden', 'dominio__orden'],
                'unique_together': {('dominio', 'dealer', 'anio')},
            },
        ),
    ]
