from rest_framework import serializers


class InventarioRefaccionesObsolescenciaSerializer(serializers.Serializer):
    agencia = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    qt_inventario = serializers.DecimalField(max_digits=18, decimal_places=4, allow_null=True, required=False)
    cod_linha_prod = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    localizacao = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    cod_produto = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    nm_produto = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    unidade = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    qtde_estoque = serializers.DecimalField(max_digits=18, decimal_places=4, allow_null=True, required=False)
    vr_estoque = serializers.DecimalField(max_digits=18, decimal_places=2, allow_null=True, required=False)
    vr_unitario_medio = serializers.DecimalField(max_digits=18, decimal_places=4, allow_null=True, required=False)
    qt_reservada = serializers.DecimalField(max_digits=18, decimal_places=4, allow_null=True, required=False)
    qt_pedida = serializers.DecimalField(max_digits=18, decimal_places=4, allow_null=True, required=False)
    grupo_principal = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    subgrupo = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    nombre_estandarizado = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    categoria = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    observacion = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    fecha_ultima_venta = serializers.DateField(allow_null=True, required=False)
    fecha_ult_comp_prod = serializers.DateField(allow_null=True, required=False)
    fecha_ult_ped_prod = serializers.DateField(allow_null=True, required=False)
    fecha_ult_actu_prod = serializers.DateField(allow_null=True, required=False)
    fecha_regis_refac = serializers.DateField(allow_null=True, required=False)
    fecha_inventario_refac = serializers.DateField(allow_null=True, required=False)
    fecha_primera_compra_refac = serializers.DateField(allow_null=True, required=False)
    fecha_actualizacion_refac = serializers.DateField(allow_null=True, required=False)
    vr_uni_ult_cpa = serializers.DecimalField(max_digits=18, decimal_places=4, allow_null=True, required=False)
    fecha_referencia = serializers.DateField(allow_null=True, required=False)
    dias_desde_ultimo_movimiento = serializers.IntegerField(allow_null=True, required=False)
    capa_obsolescencia = serializers.CharField(allow_null=True, allow_blank=True, required=False)
    categoria_movimiento = serializers.CharField(allow_null=True, allow_blank=True, required=False)