# Generated by Django 5.2.5 on 2026-03-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0003_rename_folio_venta_pruebamanejo_folio_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(default='', max_length=120)),
                ('chasis', models.CharField(default='', max_length=120)),
                ('producto_long_drive', models.CharField(default='', max_length=120)),
                ('tipo_venta', models.CharField(default='', max_length=100)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='long_drive', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'long_drive',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(default='', max_length=120)),
                ('id_soli_cred', models.CharField(default='', max_length=120)),
                ('producto_financiero', models.CharField(default='', max_length=120)),
                ('plazo_meses', models.CharField(default='', max_length=50)),
                ('monto_financiero', models.CharField(default='', max_length=120)),
                ('auto_interes', models.CharField(default='', max_length=255)),
                ('canal_origen', models.CharField(default='', max_length=200)),
                ('asesor_ventas', models.CharField(default='', max_length=200)),
                ('estado_financiamiento', models.CharField(default='', max_length=200)),
                ('estado_compra', models.CharField(default='', max_length=200)),
                ('fecha_respuesta', models.DateTimeField(null=True)),
                ('comentarios', models.TextField(default='', max_length=2000)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_credito', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'solicitud_credito',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
    ]
