# Generated by Django 5.2.5 on 2026-03-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financieros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longdrive',
            name='agencia',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='agencia',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='asesor_ventas',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='comentarios',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_financiero',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='plazo_meses',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
