# Generated by Django 5.2.5 on 2026-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financieros', '0002_alter_longdrive_agencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='canal_origen',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_financiero',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='plazo_meses',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
