# Generated by Django 5.2.5 on 2026-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financieros', '0003_alter_solicitudcredito_canal_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='comentarios',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
