# Generated by Django 5.2.5 on 2026-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financieros', '0004_alter_solicitudcredito_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='asesor_ventas',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='comentarios',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_financiero',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='plazo_meses',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
