# Generated by Django 6.0.4 on 2026-09-01 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financieros', '0005_alter_solicitudcredito_asesor_ventas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longdrive',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
