# Generated by Django 5.2.5 on 2026-09-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financieros', '0006_alter_longdrive_creado_alter_solicitudcredito_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='longdrive',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='apellido_materno_representante_legal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='apellido_materno_usuario_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='apellido_materno_usuario_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='apellido_paterno_representante_legal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='apellido_paterno_usuario_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='apellido_paterno_usuario_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='autorizacion_cargo_cuenta_bancaria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='aviso_privacidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='calle_numero',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='clave_comercial',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='cobertura',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='compania',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='concesionario',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='condicion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='correo_electronico',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='correo_electronico_usuario_1',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='correo_electronico_usuario_2',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='entidad_federativa_estado',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='estatus_certificado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='estatus_link_openpay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='estatus_pago',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='estatus_pago_openpay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='fecha_nacimiento_constitucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='fecha_nacimiento_representante_legal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='fecha_pago_openpay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='fecha_saga',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='forma_pago',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='meses_sin_intereses',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='motor',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='municipio_delegacion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='nombre_razon_social',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='numero_certificado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='numero_cliente',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='numero_contrato',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='numero_serie',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='pais_nacimiento_constitucion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='precio_con_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='precio_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='primer_nombre_representante_legal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='primer_nombre_usuario_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='primer_nombre_usuario_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='regimen_fiscal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='requiere_factura',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='segundo_nombre_representante_legal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='segundo_nombre_usuario_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='segundo_nombre_usuario_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='telefono_celular',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='terminos_condiciones',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='tipo_cliente',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='tipo_uso',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='uso_cfdi',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='longdrive',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
