# Generated by Django 5.2.5 on 2026-09-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financieros', '0008_migrar_longdrive_formato_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longdrive',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='longdrive',
            name='chasis',
        ),
        migrations.RemoveField(
            model_name='longdrive',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='longdrive',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='longdrive',
            name='producto_long_drive',
        ),
        migrations.RemoveField(
            model_name='longdrive',
            name='tipo_venta',
        ),
    ]
