# Generated by Django 6.0.4 on 2026-08-31 16:16

import django.core.validators
import django.db.models.deletion
import gestion_inversion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaMarketing',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=gestion_inversion.models.ruta_factura, validators=[django.core.validators.FileExtensionValidator(['pdf']), gestion_inversion.models.validar_pdf_real])),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(default='application/pdf', max_length=150)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('procesada', 'Procesada'), ('error', 'Error')], db_index=True, default='pendiente', max_length=20)),
                ('error_analisis', models.TextField(blank=True, default='')),
                ('creado_por', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('emisor_razon_social', models.CharField(blank=True, default='', max_length=300)),
                ('emisor_rfc', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('emisor_regimen_fiscal', models.CharField(blank=True, default='', max_length=300)),
                ('emisor_domicilio', models.TextField(blank=True, default='')),
                ('receptor_razon_social', models.CharField(blank=True, default='', max_length=300)),
                ('receptor_rfc', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('receptor_uso_cfdi', models.CharField(blank=True, default='', max_length=200)),
                ('uuid_cfdi', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('folio', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('fecha_factura', models.DateField(blank=True, db_index=True, null=True)),
                ('moneda', models.CharField(blank=True, default='MXN', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=100)),
                ('forma_pago', models.CharField(blank=True, default='', max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('resultado_ia', models.JSONField(blank=True, default=dict)),
                ('analizado', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analisis_facturas',
                'ordering': ['-creado', '-id_factura'],
                'managed': True,
                'indexes': [models.Index(fields=['estado', 'creado'], name='fact_estado_creado_idx'), models.Index(fields=['emisor_rfc', 'fecha_factura'], name='fact_emisor_fecha_idx'), models.Index(fields=['receptor_rfc', 'fecha_factura'], name='fact_receptor_fecha_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('clave', models.CharField(blank=True, default='', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unidad', models.CharField(blank=True, default='', max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('clasificacion', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Posicionamiento', 'Posicionamiento'), ('Consumo Interno', 'Consumo Interno'), ('Eventos y Prospección', 'Eventos y Prospección')], db_index=True, default='', max_length=100)),
                ('sitio', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('motivo', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='gestion_inversion.facturamarketing')),
            ],
            options={
                'db_table': 'analisis_facturas_conceptos',
                'ordering': ['orden', 'id_concepto'],
                'managed': True,
                'indexes': [models.Index(fields=['factura', 'orden'], name='fact_concepto_fact_idx'), models.Index(fields=['clasificacion', 'sitio'], name='fact_concepto_clas_idx')],
                'constraints': [models.UniqueConstraint(fields=('factura', 'orden'), name='fact_concepto_orden_unico')],
            },
        ),
    ]
