# Generated by Django 6.0.4 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturamarketing',
            name='dealer',
            field=models.CharField(blank=True, choices=[('VW Cordoba', 'VW Cordoba'), ('VW Orizaba', 'VW Orizaba'), ('VW Tuxpan', 'VW Tuxpan'), ('VW Poza Rica', 'VW Poza Rica'), ('VW Tuxtepec', 'VW Tuxtepec')], db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='facturamarketing',
            name='departamento',
            field=models.CharField(blank=True, choices=[('Nuevos', 'Nuevos'), ('Usados', 'Usados'), ('Comerciales', 'Comerciales'), ('Servicio', 'Servicio'), ('HyP', 'HyP')], db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='facturamarketing',
            index=models.Index(fields=['dealer', 'departamento', 'fecha_factura'], name='fact_dealer_depto_idx'),
        ),
    ]
