# Generated by Django 5.2.5 on 2026-02-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(db_index=True, max_length=32, unique=True)),
                ('correo', models.CharField(blank=True, default='', max_length=200)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_hora_cita', models.DateTimeField(blank=True, null=True)),
                ('fuerza', models.CharField(blank=True, default='', max_length=120)),
                ('asistencia', models.BooleanField(default=False)),
                ('be_back', models.BooleanField(default=False)),
                ('tipo_cita', models.CharField(blank=True, default='', max_length=120)),
                ('fuente_prospeccion', models.CharField(blank=True, default='', max_length=120)),
                ('asesor_solicita', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_asignado', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_atendio', models.CharField(blank=True, default='', max_length=200)),
                ('folio_venta', models.CharField(blank=True, default='', max_length=200)),
                ('num_serie', models.CharField(blank=True, default='', max_length=200)),
                ('estado_ingreso', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_venta', models.CharField(blank=True, default='', max_length=200)),
                ('registro_salesforce', models.BooleanField(default=False)),
                ('comentarios', models.CharField(blank=True, default='', max_length=2000)),
                ('comentarios_cliente', models.CharField(blank=True, default='', max_length=2000)),
            ],
            options={
                'db_table': 'citas',
                'managed': True,
            },
        ),
    ]
