# Generated by Django 5.2.5 on 2026-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='telefono',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
