# Generated by Django 5.2.5 on 2026-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropiso',
            old_name='folio_venta',
            new_name='folio',
        ),
    ]
