# Generated by Django 5.2.5 on 2026-03-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_rename_folio_venta_registropiso_folio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruebamanejo',
            old_name='folio_venta',
            new_name='folio_salida',
        ),
    ]
