# Generated by Django 5.2.5 on 2026-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_citas_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='asesor_digital',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
