# Generated by Django 5.2.5 on 2026-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_citas_asesor_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitasPiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(db_index=True, max_length=32)),
                ('correo', models.CharField(blank=True, default='', max_length=200)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_hora_cita', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('be_back', models.BooleanField(default=False)),
                ('fuente_prospeccion', models.CharField(blank=True, default='', max_length=120)),
                ('asesor_piso', models.CharField(blank=True, default='', max_length=200)),
                ('folio_venta', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_venta', models.CharField(blank=True, default='', max_length=200)),
                ('estado_ingreso', models.CharField(blank=True, default='', max_length=120)),
                ('comentarios_cliente', models.CharField(blank=True, default='', max_length=2000)),
            ],
            options={
                'db_table': 'citas_piso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PruebasManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(db_index=True, max_length=32)),
                ('correo', models.CharField(blank=True, default='', max_length=200)),
                ('auto_interes', models.CharField(blank=True, default='', max_length=255)),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_hora_cita', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('num_serie', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_piso', models.CharField(blank=True, default='', max_length=200)),
                ('comentarios_cliente', models.CharField(blank=True, default='', max_length=2000)),
                ('folio_venta', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'pruebas_manejo',
                'managed': True,
            },
        ),
    ]
