# Generated by Django 5.2.5 on 2026-03-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_rename_folio_venta_pruebamanejo_folio_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('vin', models.CharField(blank=True, default='', max_length=2000)),
                ('modelo_version', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_hora_entrega', models.DateTimeField(blank=True, null=True)),
                ('entrega_reportada', models.BooleanField(default=False)),
                ('asesor_ventas', models.CharField(blank=True, default='', max_length=200)),
                ('preparada_por', models.CharField(blank=True, default='', max_length=2000)),
                ('id_cliente_sf_nadin', models.CharField(blank=True, default='', max_length=2000)),
                ('id_cliente_sf_dms', models.CharField(blank=True, default='', max_length=2000)),
                ('comentarios', models.CharField(blank=True, default='', max_length=2000)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'entregas',
                'managed': True,
            },
        ),
    ]
