# Generated by Django 6.0.4 on 2026-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_entregas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entregas',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
