# Generated by Django 6.0.4 on 2026-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_entregas_color_entregas_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_venta',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='entregas',
            name='tipo_venta',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
