# Generated by Django 6.0.4 on 2026-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_tipo_venta_entregas_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='agendado_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
