# Generated by Django 6.0.4 on 2026-06-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_agendado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='agendado_por',
        ),
    ]
