# Generated by Django 6.0.4 on 2026-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_remove_cita_agendado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
