# Generated by Django 6.0.4 on 2026-07-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_entregas_kilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cita',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
