# Generated by Django 6.0.4 on 2026-08-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_cita_motivo_cita'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora_cita', 'asesor_digital'], name='citas_fecha_asesor_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['agencia', 'fecha_hora_cita'], name='citas_agencia_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='entregas',
            index=models.Index(fields=['fecha_hora_entrega', 'entrega_reportada'], name='ent_fecha_report_idx'),
        ),
        migrations.AddIndex(
            model_name='entregas',
            index=models.Index(fields=['agencia', 'fecha_hora_entrega'], name='ent_agencia_fecha_idx'),
        ),
    ]
