# Generated by Django 6.0.4 on 2026-06-30 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrmConformidad', '0015_alter_rol_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramaFlujo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('pasos', models.JSONField(blank=True, default=list)),
                ('nodos', models.JSONField(blank=True, default=list)),
                ('conexiones', models.JSONField(blank=True, default=list)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('total_pasos', models.PositiveIntegerField(default=0)),
                ('total_nodos', models.PositiveIntegerField(default=0)),
                ('total_conexiones', models.PositiveIntegerField(default=0)),
                ('total_decisiones', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas_flujo', to='CrmConformidad.usuario')),
            ],
            options={
                'db_table': 'flujo_diagramas_flujo',
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['usuario', '-actualizado_en'], name='flujo_diagr_usuario_666bb9_idx'), models.Index(fields=['nombre'], name='flujo_diagr_nombre_e243b6_idx')],
            },
        ),
    ]
