# Generated by Django 6.0.4 on 2026-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaJDPower',
            fields=[
                ('id_ventas', models.BigIntegerField(db_column='id_ventas', primary_key=True, serialize=False)),
                ('id_muestra', models.CharField(blank=True, db_column='id_muestra', max_length=50, null=True)),
                ('id_encuesta', models.CharField(blank=True, db_column='id_encuesta', max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, db_column='tipo', max_length=50, null=True)),
                ('canal_envio', models.CharField(blank=True, db_column='canal_envio', max_length=50, null=True)),
                ('estatus', models.CharField(blank=True, db_column='estatus', max_length=50, null=True)),
                ('chasis', models.CharField(blank=True, db_column='chasis', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='modelo', max_length=250, null=True)),
                ('anio_vehiculo', models.IntegerField(blank=True, db_column='anio_vehiculo', null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=50, null=True)),
                ('zona', models.CharField(blank=True, db_column='zona', max_length=50, null=True)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=50, null=True)),
                ('codigo_concesionaria', models.CharField(blank=True, db_column='codigo_concesionaria', max_length=50, null=True)),
                ('concesionaria', models.CharField(blank=True, db_column='concesionaria', max_length=100, null=True)),
                ('id_asesor', models.CharField(blank=True, db_column='id_asesor', max_length=50, null=True)),
                ('vwsf', models.CharField(blank=True, db_column='vwsf', max_length=50, null=True)),
                ('s1_entrega_vehiculo', models.CharField(blank=True, db_column='s1_entrega_vehiculo', max_length=50, null=True)),
                ('pn1_forma_compra', models.CharField(blank=True, db_column='pn1_forma_compra', max_length=50, null=True)),
                ('pn2_empresa_financiamiento', models.CharField(blank=True, db_column='pn2_empresa_financiamiento', max_length=100, null=True)),
                ('q1_satisfaccion_general', models.IntegerField(blank=True, db_column='Q1_satisfaccion_general', null=True)),
                ('q1_1_razones_calificacion', models.TextField(blank=True, db_column='Q1_1_razones_calificacion', null=True)),
                ('qr_2_1_proceso_entrega', models.IntegerField(blank=True, db_column='QR_2_1_proceso_entrega', null=True)),
                ('qr_2_1_1_efectividad_explicacion', models.IntegerField(blank=True, db_column='QR_2_1_1_efectividad_explicacion', null=True)),
                ('qr_2_1_2_puntualidad_entrega', models.IntegerField(blank=True, db_column='QR_2_1_2_puntualidad_entrega', null=True)),
                ('qr_2_1_3_condiciones_vehiculo', models.IntegerField(blank=True, db_column='QR_2_1_3_condiciones_vehiculo', null=True)),
                ('qr_2_1_4_conexion_bluetooth', models.IntegerField(blank=True, db_column='QR_2_1_4_conexion_bluetooth', null=True)),
                ('qr_2_2_atencion_personal', models.IntegerField(blank=True, db_column='QR_2_2_atencion_personal', null=True)),
                ('qr_2_2_1_conocimiento_vehiculo', models.IntegerField(blank=True, db_column='QR_2_2_1_conocimiento_vehiculo', null=True)),
                ('qr_2_2_2_amabilidad', models.IntegerField(blank=True, db_column='QR_2_2_2_amabilidad', null=True)),
                ('qr_2_2_3_respuesta', models.IntegerField(blank=True, db_column='QR_2_2_3_respuesta', null=True)),
                ('qr_2_2_4_comunicacion_fuera', models.IntegerField(blank=True, db_column='QR_2_2_4_comunicacion_fuera', null=True)),
                ('qr_2_2_5_uso_tecnologia', models.IntegerField(blank=True, db_column='QR_2_2_5_uso_tecnologia', null=True)),
                ('qr_2_2_6_info_tiempo_entrega', models.IntegerField(blank=True, db_column='QR_2_2_6_info_tiempo_entrega', null=True)),
                ('qr_2_3_instalaciones', models.IntegerField(blank=True, db_column='QR_2_3_instalaciones', null=True)),
                ('qr_2_3_1_apariencia', models.IntegerField(blank=True, db_column='QR_2_3_1_apariencia', null=True)),
                ('qr_2_3_2_facilidad_inventario', models.IntegerField(blank=True, db_column='QR_2_3_2_facilidad_inventario', null=True)),
                ('qr_2_3_3_variedad_modelos', models.IntegerField(blank=True, db_column='QR_2_3_3_variedad_modelos', null=True)),
                ('qr_2_3_4_calidad_amenidades', models.IntegerField(blank=True, db_column='QR_2_3_4_calidad_amenidades', null=True)),
                ('qr_2_3_5_opciones_estacionamiento', models.IntegerField(blank=True, db_column='QR_2_3_5_opciones_estacionamiento', null=True)),
                ('qr_2_4_documentacion', models.IntegerField(blank=True, db_column='QR_2_4_documentacion', null=True)),
                ('qr_2_4_1_claridad_documentos', models.IntegerField(blank=True, db_column='QR_2_4_1_claridad_documentos', null=True)),
                ('qr_2_4_2_transparencia_papeleo', models.IntegerField(blank=True, db_column='QR_2_4_2_transparencia_papeleo', null=True)),
                ('qr_2_4_3_prontitud_papeleo', models.IntegerField(blank=True, db_column='QR_2_4_3_prontitud_papeleo', null=True)),
                ('qr_2_5_negociacion', models.IntegerField(blank=True, db_column='QR_2_5_negociacion', null=True)),
                ('qr_2_5_1_acuerdo_precio', models.IntegerField(blank=True, db_column='QR_2_5_1_acuerdo_precio', null=True)),
                ('qr_2_5_2_precio_justo', models.IntegerField(blank=True, db_column='QR_2_5_2_precio_justo', null=True)),
                ('qr_2_5_3_comodidad_negociacion', models.IntegerField(blank=True, db_column='QR_2_5_3_comodidad_negociacion', null=True)),
                ('q3_comentarios_adicionales', models.TextField(blank=True, db_column='Q3_comentarios_adicionales', null=True)),
                ('p1_satisfaccion_producto', models.IntegerField(blank=True, db_column='P1_satisfaccion_producto', null=True)),
                ('p1_1_comentarios_auto', models.TextField(blank=True, db_column='P1_1_comentarios_auto', null=True)),
                ('p3_recomendacion_distribuidor', models.IntegerField(blank=True, db_column='P3_recomendacion_distribuidor', null=True)),
                ('q8_transferencia_datos', models.CharField(blank=True, db_column='Q8_transferencia_datos', max_length=50, null=True)),
                ('q10_autoriza_publicacion', models.CharField(blank=True, db_column='Q10_autoriza_publicacion', max_length=50, null=True)),
                ('fecha_registro', models.DateField(blank=True, db_column='fecha_registro', null=True)),
                ('fecha_entrega', models.DateField(blank=True, db_column='fecha_entrega', null=True)),
                ('fecha_encuesta', models.DateTimeField(blank=True, db_column='fecha_encuesta', null=True)),
                ('periodo', models.DateField(blank=True, db_column='periodo', null=True)),
            ],
            options={
                'verbose_name': 'Encuesta JD Power',
                'verbose_name_plural': 'Encuestas JD Power',
                'db_table': 'encuesta_jdpowerv',
                'managed': False,
            },
        ),
    ]
