# Generated by Django 5.2.5 on 2026-02-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('chasis', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=255)),
                ('OS_EXP', models.IntegerField()),
                ('agencia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteConformidad',
            fields=[
                ('id_exp', models.AutoField(primary_key=True, serialize=False)),
                ('linea', models.CharField(max_length=255)),
                ('fecha_atencion', models.DateField()),
                ('fecha_reclamacion', models.DateField()),
                ('origen', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=70)),
                ('problema', models.TextField()),
                ('recopilacion', models.TextField()),
                ('caso', models.CharField(max_length=255)),
                ('raiz', models.CharField(max_length=100)),
                ('documentacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='CrmConformidad.cliente')),
            ],
            options={
                'db_table': 'expediente_conformidad',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDocumento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='crm_docs/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(db_column='id_exp', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='CrmConformidad.expedienteconformidad')),
            ],
            options={
                'db_table': 'expediente_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=70, null=True)),
                ('usuario', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('agencia', models.CharField(max_length=100)),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.PROTECT, to='CrmConformidad.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
