# Generated by Django 5.2.5 on 2026-02-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='expedienteconformidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='expedientedocumento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
