# Generated by Django 5.2.5 on 2026-02-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0002_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedientedocumento',
            options={},
        ),
    ]
