# Generated by Django 5.2.5 on 2026-02-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0003_alter_expedientedocumento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedientedocumento',
            options={'managed': False},
        ),
    ]
