# Generated by Django 5.2.5 on 2026-02-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0004_alter_expedientedocumento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedienteconformidad',
            options={'managed': True},
        ),
    ]
