# Generated by Django 5.2.5 on 2026-02-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0005_alter_expedienteconformidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedienteconformidad',
            options={'managed': False},
        ),
    ]
