# Generated by Django 5.2.5 on 2026-03-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0006_alter_expedienteconformidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='expedienteconformidad',
            options={'managed': True},
        ),
    ]
