# Generated by Django 5.2.5 on 2026-03-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0007_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='OS_EXP',
            new_name='os_exp',
        ),
        migrations.RemoveField(
            model_name='expedienteconformidad',
            name='documentacion',
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='fecha_contacto_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='fecha_contacto_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='fecha_contacto_3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='fecha_contacto_cierre',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='obs_contacto_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='obs_contacto_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='obs_contacto_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expedienteconformidad',
            name='obs_contacto_cierre',
            field=models.TextField(null=True),
        ),
    ]
