# Generated by Django 5.2.5 on 2026-03-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0008_rename_os_exp_cliente_os_exp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
