# Generated by Django 6.0.4 on 2026-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0010_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='agencia',
            field=models.CharField(max_length=255),
        ),
    ]
