# Generated by Django 6.0.4 on 2026-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0012_auto_20260605_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasetoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
