# Generated by Django 5.2.5 on 2026-06-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0013_alter_firebasetoken_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasetoken',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firebase_tokens', to='CrmConformidad.usuario'),
        ),
    ]
