# Generated by Django 6.0.4 on 2026-06-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0014_alter_firebasetoken_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
    ]
