# Generated by Django 6.0.4 manually for the "interfaces" per-user override.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0016_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='interfaces',
            field=models.JSONField(blank=True, null=True),
        ),
    ]