# Generated by Django 6.0.4 on 2026-09-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0017_usuario_interfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/%Y/%m/'),
        ),
    ]
