# Generated by Django 5.2.5 on 2026-02-26 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CrmConformidad', '0006_alter_expedienteconformidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_propios', to='CrmConformidad.usuario')),
            ],
            options={
                'db_table': 'clickup_equipo',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clickup.equipo')),
            ],
            options={
                'db_table': 'clickup_proyectos',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='clickup.proyecto')),
            ],
            options={
                'db_table': 'clickup_listas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
                ('vence_en', models.DateTimeField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_clickup_creadas', to='CrmConformidad.usuario')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='clickup.lista')),
            ],
            options={
                'db_table': 'clickup_tareas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TareaAsignada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignados', to='clickup.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_clickup_asignadas', to='CrmConformidad.usuario')),
            ],
            options={
                'db_table': 'clickup_tarea_asignada',
            },
        ),
        migrations.CreateModel(
            name='InvitacionEquipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=255)),
                ('rol', models.CharField(default='MEMBER', max_length=12)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('REVOKED', 'Revocada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('aceptado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_equipo_aceptadas', to='CrmConformidad.usuario')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='clickup.equipo')),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_equipo_enviadas', to='CrmConformidad.usuario')),
            ],
            options={
                'db_table': 'clickup_invitacion_equipo',
                'indexes': [models.Index(fields=['equipo', 'correo'], name='clickup_inv_equipo__38bd47_idx'), models.Index(fields=['token'], name='clickup_inv_token_4cebe4_idx'), models.Index(fields=['estado'], name='clickup_inv_estado_bdbc80_idx')],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('MEMBER', 'Miembro'), ('VIEWER', 'Lector')], default='MEMBER', max_length=12)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='clickup.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_equipo', to='CrmConformidad.usuario')),
            ],
            options={
                'db_table': 'clickup_miembro_equipo',
                'constraints': [models.UniqueConstraint(fields=('equipo', 'usuario'), name='uq_clickup_miembro_equipo_usuario')],
            },
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('equipo', 'nombre'), name='uq_clickup_proyecto_equipo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='lista',
            constraint=models.UniqueConstraint(fields=('proyecto', 'nombre'), name='uq_clickup_lista_proyecto_nombre'),
        ),
        migrations.AddConstraint(
            model_name='tareaasignada',
            constraint=models.UniqueConstraint(fields=('tarea', 'usuario'), name='uq_clickup_tarea_asignada_tarea_usuario'),
        ),
    ]
