# Generated by Django 5.2.5 on 2026-03-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0008_rename_os_exp_cliente_os_exp_and_more'),
        ('clickup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionClickup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TEAM_INVITE', 'Invitación a equipo'), ('TASK_ASSIGNED', 'Tarea asignada'), ('TASK_UPDATED', 'Tarea actualizada')], max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('DISMISSED', 'Descartada'), ('READ', 'Leída')], default='PENDING', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clickup_notificacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='invitacionequipo',
            name='usuario_invitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_clickup_recibidas', to='CrmConformidad.usuario'),
        ),
        migrations.AlterField(
            model_name='invitacionequipo',
            name='correo',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invitacionequipo',
            name='estado',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('REVOKED', 'Revocada'), ('EXPIRED', 'Expirada')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitacionequipo',
            name='rol',
            field=models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('MEMBER', 'Miembro'), ('VIEWER', 'Lector')], default='MEMBER', max_length=12),
        ),
        migrations.AddIndex(
            model_name='invitacionequipo',
            index=models.Index(fields=['usuario_invitado', 'estado'], name='clickup_inv_usuario_af0068_idx'),
        ),
        migrations.AddField(
            model_name='notificacionclickup',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clickup.equipo'),
        ),
        migrations.AddField(
            model_name='notificacionclickup',
            name='invitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clickup.invitacionequipo'),
        ),
        migrations.AddField(
            model_name='notificacionclickup',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clickup.proyecto'),
        ),
        migrations.AddField(
            model_name='notificacionclickup',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clickup.tarea'),
        ),
        migrations.AddField(
            model_name='notificacionclickup',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_clickup', to='CrmConformidad.usuario'),
        ),
        migrations.AddIndex(
            model_name='notificacionclickup',
            index=models.Index(fields=['usuario', 'creado_en'], name='clickup_not_usuario_c707f4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionclickup',
            index=models.Index(fields=['usuario', 'estado'], name='clickup_not_usuario_d2768d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionclickup',
            index=models.Index(fields=['tipo'], name='clickup_not_tipo_7ea7d4_idx'),
        ),
    ]
