# Generated by Django 5.2.5 on 2026-03-19 17:05

import clickup.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmConformidad', '0008_rename_os_exp_cliente_os_exp_and_more'),
        ('clickup', '0002_notificacionclickup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionclickup',
            name='tipo',
            field=models.CharField(choices=[('TEAM_INVITE', 'Invitación a equipo'), ('TASK_ASSIGNED', 'Tarea asignada'), ('TASK_UPDATED', 'Tarea actualizada'), ('BUG_REPORTED', 'Error reportado')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReporteIncidencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BUG', 'Error'), ('SUGGESTION', 'Sugerencia')], default='BUG', max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_incidencia', to='clickup.equipo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_incidencia', to='clickup.proyecto')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_incidencia_creados', to='CrmConformidad.usuario')),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_incidencia', to='clickup.tarea')),
            ],
            options={
                'db_table': 'clickup_reporte_incidencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaTarea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BUG', 'Evidencia del bug'), ('RESOLUTION', 'Evidencia de solución')], max_length=20)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(upload_to=clickup.models.evidencia_upload_to)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_clickup_subidas', to='CrmConformidad.usuario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='clickup.tarea')),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='clickup.reporteincidencia')),
            ],
            options={
                'db_table': 'clickup_evidencia_tarea',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='reporteincidencia',
            index=models.Index(fields=['tipo', 'estado'], name='clickup_rep_tipo_7da469_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteincidencia',
            index=models.Index(fields=['creado_en'], name='clickup_rep_creado__ed0dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteincidencia',
            index=models.Index(fields=['reportado_por'], name='clickup_rep_reporta_09568f_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciatarea',
            index=models.Index(fields=['tarea', 'tipo'], name='clickup_evi_tarea_i_201978_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenciatarea',
            index=models.Index(fields=['creado_en'], name='clickup_evi_creado__1cd75f_idx'),
        ),
    ]
