# Generated by Django 6.0.4 on 2026-05-20 17:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup', '0003_alter_notificacionclickup_tipo_reporteincidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='causa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='desarrollo_estrategia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion_problema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Por hacer', 'Por hacer'), ('En proceso', 'En proceso'), ('Hecho', 'Hecho')], default='Por hacer', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='raiz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='resultados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='clickup.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
