# Generated by Django 5.2.5 on 2026-09-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup', '0004_tarea_actualizado_en_tarea_causa_tarea_completada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroequipo',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
