# Generated by Django 6.0.4 on 2026-05-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0005_entregas_color_entregas_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, default='', max_length=120)),
                ('no_orden', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('diss', models.CharField(blank=True, default='', max_length=120)),
                ('pauta', models.TextField(blank=True, default='')),
                ('indicador_resultados', models.CharField(blank=True, default='', max_length=120)),
                ('alcance', models.CharField(blank=True, default='', max_length=120)),
                ('citado', models.CharField(blank=True, default='', max_length=120)),
                ('torre', models.CharField(blank=True, default='', max_length=120)),
                ('asesor', models.CharField(blank=True, default='', max_length=120)),
                ('nombre_cliente', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_cita', models.CharField(blank=True, default='', max_length=120)),
                ('declaracion_textual_cliente', models.TextField(blank=True, default='')),
                ('comentarios', models.TextField(blank=True, default='')),
                ('vin', models.CharField(blank=True, default='', max_length=80)),
                ('anio_vehiculo', models.CharField(blank=True, default='', max_length=10)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('medio_concertacion', models.CharField(blank=True, default='', max_length=120)),
                ('pauta_origen', models.TextField(blank=True, default='')),
                ('venta_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asesor_digital', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_piso', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ingresos', to='citas.clientecomercial')),
            ],
            options={
                'db_table': 'hoja_ingresos',
                'ordering': ['-fecha_ingreso', '-id'],
                'managed': True,
                'indexes': [models.Index(fields=['fecha_ingreso'], name='hoja_ingres_fecha_i_b47a69_idx'), models.Index(fields=['agencia'], name='hoja_ingres_agencia_ed825f_idx'), models.Index(fields=['asesor'], name='hoja_ingres_asesor_d3fe30_idx'), models.Index(fields=['asistencia'], name='hoja_ingres_asisten_1089af_idx'), models.Index(fields=['vin'], name='hoja_ingres_vin_159e1e_idx'), models.Index(fields=['no_orden'], name='hoja_ingres_no_orde_42c699_idx')],
            },
        ),
    ]
