# Generated by Django 6.0.4 on 2026-05-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaingresos',
            name='citado',
            field=models.BooleanField(default=False),
        ),
    ]
