# Generated by Django 6.0.4 on 2026-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaingresos', '0002_alter_hojaingresos_citado'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaingresos',
            name='agendado_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
