# Generated by Django 6.0.4 on 2026-07-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_entregas_kilometraje'),
        ('hojaingresos', '0003_hojaingresos_agendado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaingresos',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ingresos', to='citas.clientecomercial'),
        ),
        migrations.CreateModel(
            name='TallerActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('etapa', models.CharField(blank=True, db_index=True, default='Ingreso con Cita', max_length=80)),
                ('estatus_agenda', models.CharField(blank=True, db_index=True, default='Programado', max_length=40)),
                ('fecha_programada', models.DateField(blank=True, db_index=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tipo_bloque', models.CharField(blank=True, db_index=True, default='trabajo', max_length=40)),
                ('tipo_servicio', models.CharField(blank=True, default='', max_length=255)),
                ('comentarios_taller', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ingreso', models.OneToOneField(db_column='id_ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='taller', to='hojaingresos.hojaingresos')),
            ],
            options={
                'db_table': 'taller_actividad',
                'ordering': ['fecha_programada', 'hora_inicio', 'tecnico', 'id'],
                'indexes': [models.Index(fields=['fecha_programada', 'tecnico'], name='taller_acti_fecha_p_eee4a7_idx'), models.Index(fields=['etapa', 'fecha_programada'], name='taller_acti_etapa_f695a3_idx')],
            },
        ),
    ]
