# Generated by Django 6.0.4 on 2026-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaingresos', '0004_alter_hojaingresos_cliente_talleractividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaingresos',
            name='hora_promesa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hojaingresos',
            name='long_drive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hojaingresos',
            name='pre_picking_hecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hojaingresos',
            name='pre_picking_notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
