# Generated by Django 6.0.4 on 2026-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaingresos', '0005_hojaingresos_hora_promesa_hojaingresos_long_drive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaingresos',
            name='tipo_cita',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='talleractividad',
            name='tipo_servicio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
