# Generated by Django 6.0.4 on 2026-08-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaingresos', '0006_alter_hojaingresos_tipo_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaingresos',
            name='asistencia',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hojaingresos',
            name='citado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hojaingresos',
            name='long_drive',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
