# Generated by Django 6.0.4 on 2026-09-10 12:09

import django.db.models.deletion
import hojaingresos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojaingresos', '0007_alter_hojaingresos_asistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaIngresoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=hojaingresos.models.ruta_evidencia_hoja_ingresos)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=120)),
                ('tamanio', models.PositiveBigIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(db_column='id_ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='hojaingresos.hojaingresos')),
            ],
            options={
                'db_table': 'hoja_ingresos_evidencias',
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
