# Generated by Django 6.0.4 on 2026-05-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico_piso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traficopiso',
            name='auto_suenos',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
