# Generated by Django 6.0.4 on 2026-06-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico_piso', '0002_traficopiso_auto_suenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='traficopiso',
            name='tipo_venta',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
