# Generated by Django 6.0.4 on 2026-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicioVW',
            fields=[
                ('chassi', models.TextField(blank=True, db_column='Chassi', null=True)),
                ('cliente_veiculo', models.TextField(blank=True, db_column='Cliente_Veiculo', null=True)),
                ('marca_auto', models.TextField(blank=True, db_column='Marca_Auto', null=True)),
                ('modelo_auto', models.TextField(blank=True, db_column='Modelo_Auto', null=True)),
                ('num_os', models.TextField(db_column='Num_OS', primary_key=True, serialize=False)),
                ('fecha_os', models.DateField(blank=True, db_column='Fecha_OS', null=True)),
                ('fecha_emision', models.DateField(blank=True, db_column='Fecha_Emision', null=True)),
                ('fecha_salida', models.DateField(blank=True, db_column='Fecha_Salida', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=8, null=True)),
                ('dias_os_a_actual', models.IntegerField(blank=True, db_column='Dias_OS_A_Actual', null=True)),
                ('segmento', models.CharField(blank=True, db_column='Segmento', max_length=10, null=True)),
                ('meses_actual_a_emision', models.IntegerField(blank=True, db_column='Meses_Actual_A_Emision', null=True)),
                ('num_nota', models.TextField(blank=True, db_column='Num_Nota', null=True)),
                ('total_nota', models.TextField(blank=True, db_column='Total_Nota', null=True)),
                ('subtipo_os', models.TextField(blank=True, db_column='Subtipo_OS', null=True)),
                ('telefono', models.TextField(blank=True, db_column='telefono', null=True)),
                ('correo', models.TextField(blank=True, db_column='correo', null=True)),
                ('nombre', models.TextField(blank=True, db_column='nombre', null=True)),
                ('serie', models.TextField(blank=True, db_column='Serie', null=True)),
                ('total_servicio', models.TextField(blank=True, db_column='Total_Servicio', null=True)),
            ],
            options={
                'verbose_name': 'Orden de Servicio Retención',
                'verbose_name_plural': 'Órdenes de Servicio Retención',
                'db_table': 'Ordenes_Servicio_VW',
                'managed': False,
            },
        ),
    ]
