# Generated by Django 6.0.4 on 2026-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicioCompletaVW',
            fields=[
                ('vin', models.TextField(blank=True, db_column='VIN', db_index=True, null=True)),
                ('agencia', models.TextField(blank=True, db_column='Agencia', null=True)),
                ('fecha_venta', models.DateField(blank=True, db_column='FechaVenta', null=True)),
                ('fecha_salida', models.DateField(blank=True, db_column='FechaSalida', null=True)),
                ('numero_nota', models.TextField(blank=True, db_column='NumeroNota', null=True)),
                ('total_nota', models.DecimalField(blank=True, db_column='TotalNota', decimal_places=2, max_digits=18, null=True)),
                ('marca', models.TextField(blank=True, db_column='Marca', null=True)),
                ('modelo_codigo', models.TextField(blank=True, db_column='ModeloCodigo', null=True)),
                ('modelo_nombre', models.TextField(blank=True, db_column='ModeloNombre', null=True)),
                ('condicion_vehiculo', models.CharField(blank=True, db_column='CondicionVehiculo', max_length=10, null=True)),
                ('nombre_cliente', models.TextField(blank=True, db_column='NombreCliente', null=True)),
                ('telefono_cliente', models.TextField(blank=True, db_column='TelefonoCliente', null=True)),
                ('correo_cliente', models.TextField(blank=True, db_column='CorreoCliente', null=True)),
                ('numero_orden_servicio', models.TextField(db_column='NumeroOrdenServicio', primary_key=True, serialize=False)),
                ('tipo_orden', models.CharField(blank=True, db_column='TipoOrden', max_length=20, null=True)),
                ('subtipo_orden', models.CharField(blank=True, db_column='SubtipoOrden', max_length=20, null=True)),
                ('fecha_os', models.DateField(blank=True, db_column='FechaOS', null=True)),
                ('situacion_os', models.CharField(blank=True, db_column='SituacionOS', max_length=20, null=True)),
                ('cliente_vehiculo', models.TextField(blank=True, db_column='ClienteVeiculo', null=True)),
                ('placa_vehiculo', models.TextField(blank=True, db_column='PlacaVeiculo', null=True)),
                ('kilometraje', models.TextField(blank=True, db_column='Quilometragem', null=True)),
                ('medio_contacto', models.TextField(blank=True, db_column='MedioContacto', null=True)),
                ('total_servicio', models.DecimalField(blank=True, db_column='TotalServicio', decimal_places=2, max_digits=18, null=True)),
                ('estado_actividad', models.CharField(blank=True, db_column='EstadoActividad', max_length=20, null=True)),
                ('meses_desde_venta', models.IntegerField(blank=True, db_column='MesesDesdeVenta', null=True)),
                ('segmento', models.CharField(blank=True, db_column='Segmento', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Orden Servicio Completa',
                'verbose_name_plural': 'Órdenes Servicio Completas',
                'db_table': 'Ventas_Ordenes_Servicio_Completas_VW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenServicioVentaVW',
            fields=[
                ('vin', models.TextField(db_column='VIN', primary_key=True, serialize=False)),
                ('agencia', models.TextField(blank=True, db_column='Agencia', null=True)),
                ('fecha_venta', models.DateField(blank=True, db_column='FechaVenta', null=True)),
                ('fecha_salida', models.DateField(blank=True, db_column='FechaSalida', null=True)),
                ('numero_nota', models.TextField(blank=True, db_column='NumeroNota', null=True)),
                ('total_nota', models.DecimalField(blank=True, db_column='TotalNota', decimal_places=2, max_digits=18, null=True)),
                ('marca', models.TextField(blank=True, db_column='Marca', null=True)),
                ('modelo_codigo', models.TextField(blank=True, db_column='ModeloCodigo', null=True)),
                ('modelo_nombre', models.TextField(blank=True, db_column='ModeloNombre', null=True)),
                ('condicion_vehiculo', models.CharField(blank=True, db_column='CondicionVehiculo', max_length=10, null=True)),
                ('nombre_cliente', models.TextField(blank=True, db_column='NombreCliente', null=True)),
                ('telefono_cliente', models.TextField(blank=True, db_column='TelefonoCliente', null=True)),
                ('correo_cliente', models.TextField(blank=True, db_column='CorreoCliente', null=True)),
                ('ultima_orden_servicio', models.TextField(blank=True, db_column='UltimaOrdenServicio', null=True)),
                ('tipo_orden', models.CharField(blank=True, db_column='TipoOrden', max_length=20, null=True)),
                ('subtipo_orden', models.CharField(blank=True, db_column='SubtipoOrden', max_length=20, null=True)),
                ('fecha_ultima_os', models.DateField(blank=True, db_column='FechaUltimaOS', null=True)),
                ('situacion_os', models.CharField(blank=True, db_column='SituacionOS', max_length=20, null=True)),
                ('cliente_vehiculo', models.TextField(blank=True, db_column='ClienteVeiculo', null=True)),
                ('placa_vehiculo', models.TextField(blank=True, db_column='PlacaVeiculo', null=True)),
                ('kilometraje', models.TextField(blank=True, db_column='Quilometragem', null=True)),
                ('medio_contacto', models.TextField(blank=True, db_column='MedioContacto', null=True)),
                ('total_ultimo_servicio', models.DecimalField(blank=True, db_column='TotalUltimoServicio', decimal_places=2, max_digits=18, null=True)),
                ('estado_actividad', models.CharField(blank=True, db_column='EstadoActividad', max_length=10, null=True)),
                ('meses_desde_venta', models.IntegerField(blank=True, db_column='MesesDesdeVenta', null=True)),
                ('segmento', models.CharField(blank=True, db_column='Segmento', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Orden Venta Retención',
                'verbose_name_plural': 'Órdenes Venta Retención',
                'db_table': 'Ordenes_Servicio_Ventas_VW',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrdenServicioVW',
        ),
    ]
