# Generated by Django 6.0.4 on 2026-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0002_ordenserviciocompletavw_ordenservicioventavw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_cliente', models.CharField(db_index=True, max_length=20)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea de cliente',
                'verbose_name_plural': 'Tareas de clientes',
                'db_table': 'retencion_tarea_cliente',
                'ordering': ['-created_at'],
            },
        ),
    ]
