# Generated by Django 6.0.4 on 2026-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0003_tareacliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareacliente',
            name='forma_contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tareacliente',
            name='motivo_contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tareacliente',
            name='resultado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
