# Generated by Django 6.0.4 on 2026-08-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0004_tareacliente_forma_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordenservicioventavw',
            table='Ordenes_Servicio_Ventas_VW_v2',
        ),
    ]
