# Generated by Django 5.2.5 on 2026-03-31 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosPiezas',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=200, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_programada_llegada', models.DateField(blank=True, null=True)),
                ('dealer', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_cliente', models.CharField(blank=True, default='', max_length=200)),
                ('asesor', models.CharField(blank=True, default='', max_length=200)),
                ('orden_servicio', models.CharField(blank=True, default='', max_length=50)),
                ('ticket_sar', models.CharField(blank=True, default='', max_length=100)),
                ('canal', models.CharField(blank=True, default='', max_length=100)),
                ('estatus', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'pedidos_piezas',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=300)),
                ('categoria', models.CharField(blank=True, default='', max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'piezas',
                'ordering': ['codigo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoPiezaDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('numero_parte', models.CharField(blank=True, default='', max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tipo_pedido', models.CharField(blank=True, default='', max_length=20)),
                ('estatus', models.CharField(blank=True, default='', max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='PedidosPiezas.pedidospiezas')),
                ('pieza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='PedidosPiezas.piezas')),
            ],
            options={
                'db_table': 'pedidos_piezas_detalle',
                'ordering': ['id_detalle'],
                'managed': True,
            },
        ),
    ]
