# Generated by Django 5.2.5 on 2026-04-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosPiezas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezas',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='piezas',
            name='categoria',
        ),
    ]
