# Generated by Django 5.2.5 on 2026-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidosPiezas', '0002_remove_piezas_activo_remove_piezas_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopiezadetalle',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
