# Generated by Django 5.2.5 on 2026-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_cliente', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_atendio', models.CharField(blank=True, default='', max_length=200)),
                ('motivo_visita', models.CharField(blank=True, default='', max_length=200)),
                ('atencion_asesor', models.IntegerField(blank=True, default=0)),
                ('seguimiento_asesor', models.IntegerField(blank=True, default=0)),
                ('tiempo_entrega_unidad', models.IntegerField(blank=True, default=0)),
                ('experiencia_recepcion', models.IntegerField(blank=True, default=0)),
                ('comentario', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'encuestas_satisfaccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EncuestaServicio',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_OS_cliente', models.CharField(blank=True, default='', max_length=200)),
                ('asesor_atendio', models.CharField(blank=True, default='', max_length=200)),
                ('satisfaccion_agenda_cita', models.CharField(blank=True, default='', max_length=200)),
                ('atencion_asesor', models.IntegerField(blank=True, default=0)),
                ('percepcion_calidad_precio', models.IntegerField(blank=True, default=0)),
                ('satisfaccion_servicio_ryr', models.IntegerField(blank=True, default=0)),
                ('comentario', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'encuestas_servicio',
                'managed': True,
            },
        ),
    ]
