# Generated by Django 5.2.5 on 2026-04-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuestaservicio',
            old_name='atencion_asesor',
            new_name='satisfaccion_atencion_asesor',
        ),
    ]
