# Generated by Django 6.0.4 on 2026-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0002_rename_atencion_asesor_encuestaservicio_satisfaccion_atencion_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaPiso',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_cliente', models.CharField(blank=True, default='', max_length=200)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('asesor_atendio', models.CharField(blank=True, default='', max_length=200)),
                ('motivo_visita', models.CharField(blank=True, default='', max_length=300)),
                ('atencion_asesor', models.IntegerField(blank=True, default=0)),
                ('seguimiento_asesor', models.IntegerField(blank=True, default=0)),
                ('tiempo_entrega_unidad', models.IntegerField(blank=True, default=0)),
                ('experiencia_recepcion', models.IntegerField(blank=True, default=0)),
                ('comentario', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('id_trafico', models.IntegerField(blank=True, null=True)),
                ('flow_token', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'encuestas_piso',
                'managed': True,
            },
        ),
    ]
