# Generated by Django 6.0.4 on 2026-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encuestas', '0003_encuestapiso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuestapiso',
            old_name='experiencia_recepcion',
            new_name='amenidades',
        ),
        migrations.RenameField(
            model_name='encuestapiso',
            old_name='seguimiento_asesor',
            new_name='atencion_llegada',
        ),
        migrations.RenameField(
            model_name='encuestapiso',
            old_name='creado',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='encuestapiso',
            old_name='tiempo_entrega_unidad',
            new_name='experiencia',
        ),
        migrations.RemoveField(
            model_name='encuestapiso',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='encuestapiso',
            name='motivo_visita',
        ),
        migrations.AddField(
            model_name='encuestapiso',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='encuestapiso',
            name='contacto_post',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encuestapiso',
            name='financiamiento',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encuestapiso',
            name='medio_contacto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encuestapiso',
            name='prueba_manejo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encuestapiso',
            name='recomendacion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encuestapiso',
            name='tiempo_contacto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
